version: "3.9"
services:
  vsserver:
    image: vintage_story_server:any
    container_name: vintagestory_server
    ports:
      - "42420:42420"
    volumes:
      - ./vintage_story/data:/var/vintagestory/data
    environment:
      - SERVER_NAME="My Vintage Story Server"
      - SERVER_DESCRIPTION="A cozy place to try and survive Vintage Story"
      - MAX_CLIENTS=16
      - WELCOME_MESSAGE="Welcome {0}, may you survive well and prosper"
      - SERVER_PASSWORD=abcdef1234567
    restart: unless-stopped
