name: Versioning and Docker Image Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  assign-version:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      attestations: write
      id-token: write
    outputs:
      version: ${{ steps.semver.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          pip-install: pyyaml

      - name: Run semantic versioning
        id: semver
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 semver.py

  publish-release:
    runs-on: ubuntu-latest
    needs: assign-version
    permissions:
      packages: write
      contents: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          pip-install: pyyaml

      - name: Log in to Docker Hub
        uses: DarkMatterProductions/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: DarkMatterProductions/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: toLowerCase
        run: echo "repository=${{ github.repository }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_OUTPUT

      - id: VintageStoryVersion
        run: python3 -c "import yaml ; f = open('vintage-story-version.yaml', 'r') ; vs_version_yaml = yaml.safe_load(f) ; stable_version = vs_version_yaml['vs_stable_version'] ; print(f'version={stable_version}') ; f.close()" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        id: push
        uses: DarkMatterProductions/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ralnoc/vintagestory:${{ needs.assign-version.outputs.version }}
            ralnoc/vintagestory:${{ needs.assign-version.outputs.version }}-python3-trixie-slim
            ralnoc/vintagestory:${{ steps.VintageStoryVersion.outputs.version }}
            ralnoc/vintagestory:latest
            ghcr.io/${{steps.toLowerCase.outputs.repository}}:${{ needs.assign-version.outputs.version }}
            ghcr.io/${{steps.toLowerCase.outputs.repository}}:${{ needs.assign-version.outputs.version }}-python3-trixie-slim
            ghcr.io/${{steps.toLowerCase.outputs.repository}}:${{ steps.VintageStoryVersion.outputs.version }}
            ghcr.io/${{steps.toLowerCase.outputs.repository}}:latest